Style/Documentation:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 120

AllCops:
  Exclude:
    - 'spec/*.rb'
    - 'lib/generators/mononoke/templates/*'
    - 'test/**/*'

  TargetRubyVersion: "2.5"